"""
Documentation Generator
Generates project documentation (README, CONTRIBUTING, LICENSE) and commit messages.
"""

from typing import List, Dict, Optional
from pathlib import Path
import datetime

from src.planning.project_planner import ProjectBrief
from src.generation.ai_provider import get_ai_client
from src.database import Project


class DocGenerator:
    """Generates documentation and commit messages for projects."""
    
    def __init__(self, config):
        """
        Initialize documentation generator.
        
        Args:
            config: System configuration
        """
        self.config = config
        self.ai_client = get_ai_client(config)
    
    def generate_documentation(self, project_dir: Path, project_brief: ProjectBrief):
        """
        Generate all project documentation.
        
        Args:
            project_dir: Path to project directory
            project_brief: Project specification
        """
        # README.md is already generated by CodeGenerator, but we could enhance it here
        # or separate concerns. For now, let's focus on other docs.
        
        # transform to lowercase for consistency
        sanitized_title = project_brief.title.lower().replace(" ", "-")
        
        self._generate_license(project_dir)
        self._generate_contributing(project_dir, project_brief)
        self._generate_changelog(project_dir)
    
    def _generate_license(self, project_dir: Path):
        """Generate MIT License."""
        year = datetime.datetime.now().year
        # TODO: Get author name from config
        author = self.config.github.username or "The Author"
        
        content = f"""MIT License

Copyright (c) {year} {author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
        (project_dir / "LICENSE").write_text(content, encoding="utf-8")

    def _generate_contributing(self, project_dir: Path, project_brief: ProjectBrief):
        """Generate CONTRIBUTING.md."""
        content = f"""# Contributing to {project_brief.title}

Thank you for your interest in contributing to {project_brief.title}!

## Getting Started

1.  Fork the repository
2.  Clone your fork: `git clone https://github.com/YOUR_USERNAME/{project_brief.title.lower().replace(' ', '-')}.git`
3.  Install dependencies
4.  Create a feature branch: `git checkout -b feature/amazing-feature`

## Coding Standards

-   Follow {project_brief.primary_language} best practices
-   Write clear, commented code
-   Add unit tests for new features

## Pull Requests

1.  Push your changes: `git push origin feature/amazing-feature`
2.  Open a Pull Request
3.  Describe your changes in detail

## License

This project is licensed under the MIT License - see the LICENSE file for details.
"""
        (project_dir / "CONTRIBUTING.md").write_text(content, encoding="utf-8")

    def _generate_changelog(self, project_dir: Path):
        """Generate initial CHANGELOG.md."""
        date = datetime.datetime.now().strftime("%Y-%m-%d")
        content = f"""# Changelog

All notable changes to this project will be documented in this file.

## [0.1.0] - {date}

### Added

-   Initial project structure
-   Core functionality implementation
-   Basic documentation
-   Unit tests
"""
        (project_dir / "CHANGELOG.md").write_text(content, encoding="utf-8")

    def generate_commit_messages(self, project_brief: ProjectBrief, num_commits: int = 3) -> List[str]:
        """
        Generate semantic commit messages for the project.
        
        Args:
            project_brief: Project specification
            num_commits: Number of commits to generate
            
        Returns:
            List of commit messages
        """
        prompt = f"""Generate {num_commits} semantic commit messages for a new project:

**Project**: {project_brief.title}
**Description**: {project_brief.description}
**Technologies**: {', '.join(project_brief.technologies)}

Requirements:
- Use Conventional Commits format (e.g., feat:, fix:, docs:, chore:)
- Messages should reflect the logical progression of building the project
- First commit should be "Initial commit" or similar setup
- Messages should be descriptive but concise
- Return ONLY the messages, one per line

Example:
chore: initial project structure and configuration
feat: implement core data processing module
docs: add README and installation guide
"""

        try:
            response = self.ai_client.generate(
                prompt=prompt,
                system_message="You are a senior software engineer following strict git commit standards.",
                temperature=0.7,
                max_tokens=200
            )
            
            messages = [line.strip() for line in response.strip().split('\n') if line.strip()]
            # Ensure we have roughly the right number, fallback/trim if needed
            if not messages:
                return self._fallback_commit_messages(project_brief)
            return messages[:num_commits]
            
        except Exception as e:
            # Fallback
            return self._fallback_commit_messages(project_brief)

    def _fallback_commit_messages(self, project_brief: ProjectBrief) -> List[str]:
        """Generate basic commit messages without AI."""
        return [
            "chore: initial project structure and configuration",
            f"feat: implement core {project_brief.title} functionality",
            "docs: add README and documentation",
            "test: add unit tests",
            "chore: cleanup and final polish"
        ]
